Fix SOFLAGS
- libgtkd references gmodule too:
  ld: error: /usr/local/lib/libgtkd-3.so: undefined reference to g_module_build_path
- the -L flags may be required (e.g. for /usr/local/lib on FreeBSD),
  so use `--libs-only-l --libs-only-L` everywhere