pkg-config: list required C libs as Requires.private
This is required for dynamic linking, otherwise consumers (like Tilix) get very fun errors like
'ld: error: /usr/local/lib/libgtkd-3.so: undefined reference to g_module_build_path'.

The actual C libs themselves do fill out this field.